/**
 * Niumination Profile — README Generator
 *
 * Reads profile.config.json and generates a formatted README.md.
 */

import { readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');

const config = JSON.parse(readFileSync(join(root, 'profile.config.json'), 'utf-8'));
const p = config.profile;

const HEADER = `<!--
╔══════════════════════════════════════════════════════════════════╗
║                    GITIUMINATION — v1.0.0                       ║
║  ${p.name.padEnd(49)}║
║  ${p.headline.padEnd(49)}║
║                                                                 ║
║  Auto-generated: DO NOT EDIT THIS FILE DIRECTLY.                ║
║  Edit profile.config.json → npm run generate:readme             ║
╚══════════════════════════════════════════════════════════════════╝
-->

# 𝙶𝚒𝚝𝚒𝚞𝚖𝚒𝚗𝚊𝚝𝚒𝚘𝚗

**${p.name}** — 𝙿𝚛𝚊𝚗𝚊𝚝𝚊 𝙺𝚘𝚖𝚙𝚞𝚝𝚎𝚛 @ 𝙳𝚒𝚜𝚔𝚘𝚖𝚒𝚗𝚏𝚘 𝙰𝚌𝚎𝚑 𝚃𝚎𝚗𝚐𝚊𝚑

\`SPBE · GovTech · AI Agents · Fullstack · Open Source\`

---

## Tentang Saya

${p.about.map(a => a).join('\n\n')}

---

## Fokus Saat Ini

| Area | Deskripsi |
|------|-----------|
${config.focus.map(f => `| **${f.name}** | ${f.description} |`).join('\n')}

---

## Featured Projects

| Proyek | Fokus | Stack | Deploy |
|--------|-------|-------|--------|
${config.projects.map(proj => {
  const homepage = proj.homepage ? `🟢 [${proj.homepage.includes('vercel') ? 'Vercel' : proj.homepage.includes('niumination.github.io') ? 'GH Pages' : 'Live'}](${proj.homepage})` : '⚪ Local';
  const stack = proj.summary.split('—').pop()?.trim() || proj.focus;
  return `| [**${proj.name}**](${proj.url}) | ${proj.summary.slice(0, 60)}... | ${stack.split('.')[0] || proj.focus} | ${homepage} |`;
}).join('\n')}

---

## Tech Stack

\`\`\`
${config.techStack.join('  ')}
\`\`\`

---

## Research Direction

${p.about[1] || 'Membangun ekosistem digital untuk Aceh Tengah — SPBE, AI Agents, dan open-source governance.'}

---

## Recent Activity

<!-- ACTIVITY_START -->
Loading recent GitHub activity...
<!-- ACTIVITY_END -->

---

> *${config.footer}*

---

<details>
<summary><b>📊 GitHub Stats</b></summary>
<br>
<img src="https://github-readme-stats.vercel.app/api?username=${p.username}&show_icons=true&theme=holi&hide_border=true" alt="GitHub Stats" />
<br>
<img src="https://github-readme-stats.vercel.app/api/top-langs/?username=${p.username}&layout=compact&theme=holi&hide_border=true" alt="Top Languages" />
</details>
`;

writeFileSync(join(root, 'README.md'), HEADER, 'utf-8');
console.log('✅ README.md generated from profile.config.json');
