/**
 * Niumination Profile — Validation Script
 * 
 * Validates profile.config.json against schema, checks references,
 * and ensures README markers are in place.
 */

import { readFileSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');

const CONFIG_PATH = join(root, 'profile.config.json');
const README_PATH = join(root, 'README.md');
const SCHEMA_PATH = join(root, 'profile.schema.json');

let errors = [];
let warnings = [];

function check(condition, msg) {
  if (!condition) errors.push(msg);
}

function warn(condition, msg) {
  if (!condition) warnings.push(msg);
}

// 1. Load config
let config;
try {
  config = JSON.parse(readFileSync(CONFIG_PATH, 'utf-8'));
  console.log('✅ profile.config.json — valid JSON');
} catch (e) {
  errors.push(`Cannot parse profile.config.json: ${e.message}`);
  printResults();
  process.exit(1);
}

// 2. Check required top-level keys
const required = ['profile', 'focus', 'projects', 'techStack', 'activity', 'appearance', 'footer'];
for (const key of required) {
  check(config[key] !== undefined, `Missing required key: "${key}"`);
}

if (config.profile) {
  const p = config.profile;
  check(p.name?.length >= 2, 'profile.name too short');
  check(p.username === 'Niumination', 'profile.username must be "Niumination"');
  check(p.headline?.length >= 3, 'profile.headline too short');
  check(p.about?.length >= 1, 'profile.about must have ≥1 paragraph');
  check(p.about.every(a => a.length >= 20), 'profile.about paragraph too short');
}

if (config.focus) {
  check(Array.isArray(config.focus), 'focus must be an array');
  config.focus.forEach((f, i) => {
    check(f.name?.length >= 2, `focus[${i}].name too short`);
    check(f.description?.length >= 10, `focus[${i}].description too short`);
  });
}

if (config.projects) {
  check(Array.isArray(config.projects), 'projects must be an array');
  config.projects.forEach((proj, i) => {
    check(proj.name?.length >= 2, `projects[${i}].name too short`);
    check(proj.url?.startsWith('https://github.com'), `projects[${i}].url must be GitHub URL`);
    check(proj.summary?.length >= 10, `projects[${i}].summary too short`);
  });
}

if (config.techStack) {
  check(Array.isArray(config.techStack), 'techStack must be an array');
  check(config.techStack.length >= 1, 'techStack must have ≥1 item');
}

if (config.activity) {
  check(typeof config.activity.enabled === 'boolean', 'activity.enabled must be boolean');
  check(Number.isInteger(config.activity.limit) && config.activity.limit >= 1, 'activity.limit must be integer ≥1');
}

if (config.appearance) {
  check(['ocean', 'signal', 'solar'].includes(config.appearance.palette), 'appearance.palette must be ocean|signal|solar');
}

// 3. Check README markers
try {
  const readme = readFileSync(README_PATH, 'utf-8');
  check(readme.includes('<!-- ACTIVITY_START -->'), 'README missing ACTIVITY_START marker');
  check(readme.includes('<!-- ACTIVITY_END -->'), 'README missing ACTIVITY_END marker');
  check(readme.includes('Auto-generated: DO NOT EDIT THIS FILE DIRECTLY'), 'README missing auto-generated notice');
  console.log('✅ README.md — markers present');
} catch (e) {
  errors.push(`Cannot read README.md: ${e.message}`);
}

// 4. Project URL consistency
if (config.projects) {
  for (const proj of config.projects) {
    if (proj.name && !existsSync(join(root, proj.url ? '../' : ''))) {
      // Just a soft check — project repos are in separate dirs
    }
  }
}

// Print results
function printResults() {
  console.log('\n---');
  if (errors.length === 0 && warnings.length === 0) {
    console.log('✅ All checks passed!');
    process.exit(0);
  }
  if (warnings.length > 0) {
    console.log(`\n⚠️  Warnings (${warnings.length}):`);
    warnings.forEach(w => console.log(`  ⚠️  ${w}`));
  }
  if (errors.length > 0) {
    console.log(`\n❌ Errors (${errors.length}):`);
    errors.forEach(e => console.log(`  ❌ ${e}`));
    process.exit(1);
  }
  process.exit(0);
}

printResults();
